FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y g++ build-essential iproute2 iputils-ping net-tools

COPY . /app

RUN g++ -o satellite satellite.cpp

RUN chmod +x /app/satellite /app/control_tc.sh

# CMD ["/app/satellite"]
CMD ["/bin/bash", "-c", "sleep infinity"]
