FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y g++ build-essential

COPY . /app

RUN g++ station.cpp sta_main.cpp -o station -pthread 

RUN chmod +x /app/station /app/control.sh

# CMD ["/app/station"]
CMD ["/bin/bash", "-c", "sleep infinity"]